lang: none

script:
  - cp upload.sh upload-$ARCH.sh
  - bash ./upload.sh upload-$ARCH.sh

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
